# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/TaurusMotorV2.ui'
#
# Created: Thu Nov 11 19:30:22 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_TaurusMotorV2(object):
    def setupUi(self, TaurusMotorV2):
        TaurusMotorV2.setObjectName("TaurusMotorV2")
        TaurusMotorV2.resize(297, 272)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TaurusMotorV2.sizePolicy().hasHeightForWidth())
        TaurusMotorV2.setSizePolicy(sizePolicy)
        self.gridlayout = QtGui.QGridLayout(TaurusMotorV2)
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(0)
        self.gridlayout.setObjectName("gridlayout")
        self.TaurusGroupBox = TaurusGroupBox(TaurusMotorV2)
        self.TaurusGroupBox.setShowText(False)
        self.TaurusGroupBox.setObjectName("TaurusGroupBox")
        self.gridlayout1 = QtGui.QGridLayout(self.TaurusGroupBox)
        self.gridlayout1.setObjectName("gridlayout1")
        self.ledState = TaurusStateLed(self.TaurusGroupBox)
        self.ledState.setLedSize(24)
        self.ledState.setUseParentModel(True)
        self.ledState.setObjectName("ledState")
        self.gridlayout1.addWidget(self.ledState, 0, 0, 1, 1)
        self.labelState = TaurusValueLabel(self.TaurusGroupBox)
        self.labelState.setMinimumSize(QtCore.QSize(50, 22))
        self.labelState.setFrameShape(QtGui.QFrame.NoFrame)
        self.labelState.setFrameShadow(QtGui.QFrame.Plain)
        self.labelState.setShowQuality(False)
        self.labelState.setUseParentModel(True)
        self.labelState.setObjectName("labelState")
        self.gridlayout1.addWidget(self.labelState, 0, 1, 1, 1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.limitN = TaurusBoolLed(self.TaurusGroupBox)
        self.limitN.setUseParentModel(True)
        self.limitN.setBoolIndex(2)
        self.limitN.setObjectName("limitN")
        self.hboxlayout.addWidget(self.limitN)
        self.limitLabel = QtGui.QLabel(self.TaurusGroupBox)
        self.limitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.limitLabel.setObjectName("limitLabel")
        self.hboxlayout.addWidget(self.limitLabel)
        self.gridlayout1.addLayout(self.hboxlayout, 0, 3, 1, 1)
        self.limitP = TaurusBoolLed(self.TaurusGroupBox)
        self.limitP.setUseParentModel(True)
        self.limitP.setBoolIndex(1)
        self.limitP.setObjectName("limitP")
        self.gridlayout1.addWidget(self.limitP, 0, 4, 1, 1)
        self.positionLabel = TaurusConfigLabel(self.TaurusGroupBox)
        self.positionLabel.setUseParentModel(True)
        self.positionLabel.setObjectName("positionLabel")
        self.gridlayout1.addWidget(self.positionLabel, 1, 0, 1, 2)
        self.positionWrite = TaurusValueLineEdit(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.positionWrite.sizePolicy().hasHeightForWidth())
        self.positionWrite.setSizePolicy(sizePolicy)
        self.positionWrite.setMinimumSize(QtCore.QSize(70, 22))
        self.positionWrite.setUseParentModel(True)
        self.positionWrite.setObjectName("positionWrite")
        self.gridlayout1.addWidget(self.positionWrite, 1, 2, 1, 1)
        self.positionRead = TaurusValueLabel(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.positionRead.sizePolicy().hasHeightForWidth())
        self.positionRead.setSizePolicy(sizePolicy)
        self.positionRead.setMinimumSize(QtCore.QSize(50, 22))
        self.positionRead.setUseParentModel(True)
        self.positionRead.setObjectName("positionRead")
        self.gridlayout1.addWidget(self.positionRead, 1, 3, 1, 1)
        self.positionUnits = TaurusConfigLabel(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.positionUnits.sizePolicy().hasHeightForWidth())
        self.positionUnits.setSizePolicy(sizePolicy)
        self.positionUnits.setMinimumSize(QtCore.QSize(35, 22))
        self.positionUnits.setMaximumSize(QtCore.QSize(35, 16777215))
        self.positionUnits.setUseParentModel(True)
        self.positionUnits.setObjectName("positionUnits")
        self.gridlayout1.addWidget(self.positionUnits, 1, 4, 1, 1)
        self.velocityLabel = TaurusConfigLabel(self.TaurusGroupBox)
        self.velocityLabel.setUseParentModel(True)
        self.velocityLabel.setObjectName("velocityLabel")
        self.gridlayout1.addWidget(self.velocityLabel, 2, 0, 1, 2)
        self.velocityWrite = TaurusValueLineEdit(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityWrite.sizePolicy().hasHeightForWidth())
        self.velocityWrite.setSizePolicy(sizePolicy)
        self.velocityWrite.setMinimumSize(QtCore.QSize(70, 22))
        self.velocityWrite.setUseParentModel(True)
        self.velocityWrite.setObjectName("velocityWrite")
        self.gridlayout1.addWidget(self.velocityWrite, 2, 2, 1, 1)
        self.velocityRead = TaurusValueLabel(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityRead.sizePolicy().hasHeightForWidth())
        self.velocityRead.setSizePolicy(sizePolicy)
        self.velocityRead.setMinimumSize(QtCore.QSize(50, 22))
        self.velocityRead.setUseParentModel(True)
        self.velocityRead.setObjectName("velocityRead")
        self.gridlayout1.addWidget(self.velocityRead, 2, 3, 1, 1)
        self.velocityUnits = TaurusConfigLabel(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocityUnits.sizePolicy().hasHeightForWidth())
        self.velocityUnits.setSizePolicy(sizePolicy)
        self.velocityUnits.setMinimumSize(QtCore.QSize(35, 22))
        self.velocityUnits.setMaximumSize(QtCore.QSize(35, 16777215))
        self.velocityUnits.setUseParentModel(True)
        self.velocityUnits.setObjectName("velocityUnits")
        self.gridlayout1.addWidget(self.velocityUnits, 2, 4, 1, 1)
        self.accelLabel = TaurusConfigLabel(self.TaurusGroupBox)
        self.accelLabel.setUseParentModel(True)
        self.accelLabel.setObjectName("accelLabel")
        self.gridlayout1.addWidget(self.accelLabel, 3, 0, 1, 2)
        self.accelWrite = TaurusValueLineEdit(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accelWrite.sizePolicy().hasHeightForWidth())
        self.accelWrite.setSizePolicy(sizePolicy)
        self.accelWrite.setMinimumSize(QtCore.QSize(70, 22))
        self.accelWrite.setUseParentModel(True)
        self.accelWrite.setObjectName("accelWrite")
        self.gridlayout1.addWidget(self.accelWrite, 3, 2, 1, 1)
        self.accelRead = TaurusValueLabel(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accelRead.sizePolicy().hasHeightForWidth())
        self.accelRead.setSizePolicy(sizePolicy)
        self.accelRead.setMinimumSize(QtCore.QSize(50, 22))
        self.accelRead.setUseParentModel(True)
        self.accelRead.setObjectName("accelRead")
        self.gridlayout1.addWidget(self.accelRead, 3, 3, 1, 1)
        self.accelUnits = TaurusConfigLabel(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accelUnits.sizePolicy().hasHeightForWidth())
        self.accelUnits.setSizePolicy(sizePolicy)
        self.accelUnits.setMinimumSize(QtCore.QSize(35, 22))
        self.accelUnits.setMaximumSize(QtCore.QSize(35, 16777215))
        self.accelUnits.setUseParentModel(True)
        self.accelUnits.setObjectName("accelUnits")
        self.gridlayout1.addWidget(self.accelUnits, 3, 4, 1, 1)
        self.decelLabel = TaurusConfigLabel(self.TaurusGroupBox)
        self.decelLabel.setUseParentModel(True)
        self.decelLabel.setObjectName("decelLabel")
        self.gridlayout1.addWidget(self.decelLabel, 4, 0, 1, 2)
        self.decelWrite = TaurusValueLineEdit(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decelWrite.sizePolicy().hasHeightForWidth())
        self.decelWrite.setSizePolicy(sizePolicy)
        self.decelWrite.setMinimumSize(QtCore.QSize(70, 22))
        self.decelWrite.setUseParentModel(True)
        self.decelWrite.setObjectName("decelWrite")
        self.gridlayout1.addWidget(self.decelWrite, 4, 2, 1, 1)
        self.decelRead = TaurusValueLabel(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decelRead.sizePolicy().hasHeightForWidth())
        self.decelRead.setSizePolicy(sizePolicy)
        self.decelRead.setMinimumSize(QtCore.QSize(50, 22))
        self.decelRead.setUseParentModel(True)
        self.decelRead.setObjectName("decelRead")
        self.gridlayout1.addWidget(self.decelRead, 4, 3, 1, 1)
        self.decelUnits = TaurusConfigLabel(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decelUnits.sizePolicy().hasHeightForWidth())
        self.decelUnits.setSizePolicy(sizePolicy)
        self.decelUnits.setMinimumSize(QtCore.QSize(35, 22))
        self.decelUnits.setMaximumSize(QtCore.QSize(35, 16777215))
        self.decelUnits.setUseParentModel(True)
        self.decelUnits.setObjectName("decelUnits")
        self.gridlayout1.addWidget(self.decelUnits, 4, 4, 1, 1)
        self.offsetLabel = TaurusConfigLabel(self.TaurusGroupBox)
        self.offsetLabel.setUseParentModel(True)
        self.offsetLabel.setObjectName("offsetLabel")
        self.gridlayout1.addWidget(self.offsetLabel, 5, 0, 1, 2)
        self.offsetWrite = TaurusValueLineEdit(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offsetWrite.sizePolicy().hasHeightForWidth())
        self.offsetWrite.setSizePolicy(sizePolicy)
        self.offsetWrite.setMinimumSize(QtCore.QSize(70, 22))
        self.offsetWrite.setUseParentModel(True)
        self.offsetWrite.setObjectName("offsetWrite")
        self.gridlayout1.addWidget(self.offsetWrite, 5, 2, 1, 1)
        self.offsetRead = TaurusValueLabel(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offsetRead.sizePolicy().hasHeightForWidth())
        self.offsetRead.setSizePolicy(sizePolicy)
        self.offsetRead.setMinimumSize(QtCore.QSize(50, 22))
        self.offsetRead.setUseParentModel(True)
        self.offsetRead.setObjectName("offsetRead")
        self.gridlayout1.addWidget(self.offsetRead, 5, 3, 1, 1)
        self.offsetUnits = TaurusConfigLabel(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offsetUnits.sizePolicy().hasHeightForWidth())
        self.offsetUnits.setSizePolicy(sizePolicy)
        self.offsetUnits.setMinimumSize(QtCore.QSize(35, 22))
        self.offsetUnits.setMaximumSize(QtCore.QSize(35, 16777215))
        self.offsetUnits.setUseParentModel(True)
        self.offsetUnits.setObjectName("offsetUnits")
        self.gridlayout1.addWidget(self.offsetUnits, 5, 4, 1, 1)
        self.baseRateLabel = TaurusConfigLabel(self.TaurusGroupBox)
        self.baseRateLabel.setUseParentModel(True)
        self.baseRateLabel.setObjectName("baseRateLabel")
        self.gridlayout1.addWidget(self.baseRateLabel, 6, 0, 1, 2)
        self.baseRateWrite = TaurusValueLineEdit(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseRateWrite.sizePolicy().hasHeightForWidth())
        self.baseRateWrite.setSizePolicy(sizePolicy)
        self.baseRateWrite.setMinimumSize(QtCore.QSize(70, 22))
        self.baseRateWrite.setUseParentModel(True)
        self.baseRateWrite.setObjectName("baseRateWrite")
        self.gridlayout1.addWidget(self.baseRateWrite, 6, 2, 1, 1)
        self.baseRateRead = TaurusValueLabel(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseRateRead.sizePolicy().hasHeightForWidth())
        self.baseRateRead.setSizePolicy(sizePolicy)
        self.baseRateRead.setMinimumSize(QtCore.QSize(50, 22))
        self.baseRateRead.setUseParentModel(True)
        self.baseRateRead.setObjectName("baseRateRead")
        self.gridlayout1.addWidget(self.baseRateRead, 6, 3, 1, 1)
        self.baseRateUnits = TaurusConfigLabel(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseRateUnits.sizePolicy().hasHeightForWidth())
        self.baseRateUnits.setSizePolicy(sizePolicy)
        self.baseRateUnits.setMinimumSize(QtCore.QSize(35, 22))
        self.baseRateUnits.setMaximumSize(QtCore.QSize(35, 16777215))
        self.baseRateUnits.setUseParentModel(True)
        self.baseRateUnits.setObjectName("baseRateUnits")
        self.gridlayout1.addWidget(self.baseRateUnits, 6, 4, 1, 1)
        self.stepsUnitLabel = TaurusConfigLabel(self.TaurusGroupBox)
        self.stepsUnitLabel.setUseParentModel(True)
        self.stepsUnitLabel.setObjectName("stepsUnitLabel")
        self.gridlayout1.addWidget(self.stepsUnitLabel, 7, 0, 1, 2)
        self.stepsUnitsWrite = TaurusValueLineEdit(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepsUnitsWrite.sizePolicy().hasHeightForWidth())
        self.stepsUnitsWrite.setSizePolicy(sizePolicy)
        self.stepsUnitsWrite.setMinimumSize(QtCore.QSize(70, 22))
        self.stepsUnitsWrite.setUseParentModel(True)
        self.stepsUnitsWrite.setObjectName("stepsUnitsWrite")
        self.gridlayout1.addWidget(self.stepsUnitsWrite, 7, 2, 1, 1)
        self.stepsUnitRead = TaurusValueLabel(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepsUnitRead.sizePolicy().hasHeightForWidth())
        self.stepsUnitRead.setSizePolicy(sizePolicy)
        self.stepsUnitRead.setMinimumSize(QtCore.QSize(50, 22))
        self.stepsUnitRead.setUseParentModel(True)
        self.stepsUnitRead.setObjectName("stepsUnitRead")
        self.gridlayout1.addWidget(self.stepsUnitRead, 7, 3, 1, 1)
        self.stepsUnitUnits = TaurusConfigLabel(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepsUnitUnits.sizePolicy().hasHeightForWidth())
        self.stepsUnitUnits.setSizePolicy(sizePolicy)
        self.stepsUnitUnits.setMinimumSize(QtCore.QSize(35, 22))
        self.stepsUnitUnits.setMaximumSize(QtCore.QSize(35, 16777215))
        self.stepsUnitUnits.setUseParentModel(True)
        self.stepsUnitUnits.setObjectName("stepsUnitUnits")
        self.gridlayout1.addWidget(self.stepsUnitUnits, 7, 4, 1, 1)
        self.backlashLabel = TaurusConfigLabel(self.TaurusGroupBox)
        self.backlashLabel.setUseParentModel(True)
        self.backlashLabel.setObjectName("backlashLabel")
        self.gridlayout1.addWidget(self.backlashLabel, 8, 0, 1, 2)
        self.backlashWrite = TaurusValueLineEdit(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backlashWrite.sizePolicy().hasHeightForWidth())
        self.backlashWrite.setSizePolicy(sizePolicy)
        self.backlashWrite.setMinimumSize(QtCore.QSize(70, 22))
        self.backlashWrite.setUseParentModel(True)
        self.backlashWrite.setObjectName("backlashWrite")
        self.gridlayout1.addWidget(self.backlashWrite, 8, 2, 1, 1)
        self.backlashRead = TaurusValueLabel(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backlashRead.sizePolicy().hasHeightForWidth())
        self.backlashRead.setSizePolicy(sizePolicy)
        self.backlashRead.setMinimumSize(QtCore.QSize(50, 22))
        self.backlashRead.setUseParentModel(True)
        self.backlashRead.setObjectName("backlashRead")
        self.gridlayout1.addWidget(self.backlashRead, 8, 3, 1, 1)
        self.backlashUnits = TaurusConfigLabel(self.TaurusGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backlashUnits.sizePolicy().hasHeightForWidth())
        self.backlashUnits.setSizePolicy(sizePolicy)
        self.backlashUnits.setMinimumSize(QtCore.QSize(35, 22))
        self.backlashUnits.setMaximumSize(QtCore.QSize(35, 16777215))
        self.backlashUnits.setUseParentModel(True)
        self.backlashUnits.setObjectName("backlashUnits")
        self.gridlayout1.addWidget(self.backlashUnits, 8, 4, 1, 1)
        self.gridlayout.addWidget(self.TaurusGroupBox, 0, 0, 1, 1)

        self.retranslateUi(TaurusMotorV2)
        QtCore.QMetaObject.connectSlotsByName(TaurusMotorV2)

    def retranslateUi(self, TaurusMotorV2):
        TaurusMotorV2.setWindowTitle(QtGui.QApplication.translate("TaurusMotorV2", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.ledState.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/State", None, QtGui.QApplication.UnicodeUTF8))
        self.labelState.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/State", None, QtGui.QApplication.UnicodeUTF8))
        self.limitN.setLedColor(QtGui.QApplication.translate("TaurusMotorV2", "ORANGE", None, QtGui.QApplication.UnicodeUTF8))
        self.limitN.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Limit_switches", None, QtGui.QApplication.UnicodeUTF8))
        self.limitLabel.setText(QtGui.QApplication.translate("TaurusMotorV2", "- lim +", None, QtGui.QApplication.UnicodeUTF8))
        self.limitP.setLedColor(QtGui.QApplication.translate("TaurusMotorV2", "ORANGE", None, QtGui.QApplication.UnicodeUTF8))
        self.limitP.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Limit_switches", None, QtGui.QApplication.UnicodeUTF8))
        self.positionLabel.setSuffixText(QtGui.QApplication.translate("TaurusMotorV2", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.positionLabel.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Position?configuration=label", None, QtGui.QApplication.UnicodeUTF8))
        self.positionWrite.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Position", None, QtGui.QApplication.UnicodeUTF8))
        self.positionRead.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Position", None, QtGui.QApplication.UnicodeUTF8))
        self.positionUnits.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Position?configuration=unit", None, QtGui.QApplication.UnicodeUTF8))
        self.velocityLabel.setSuffixText(QtGui.QApplication.translate("TaurusMotorV2", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.velocityLabel.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Velocity?configuration=label", None, QtGui.QApplication.UnicodeUTF8))
        self.velocityWrite.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.velocityRead.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.velocityUnits.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Velocity?configuration=unit", None, QtGui.QApplication.UnicodeUTF8))
        self.accelLabel.setSuffixText(QtGui.QApplication.translate("TaurusMotorV2", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.accelLabel.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Acceleration?configuration=label", None, QtGui.QApplication.UnicodeUTF8))
        self.accelWrite.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Acceleration", None, QtGui.QApplication.UnicodeUTF8))
        self.accelRead.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Acceleration", None, QtGui.QApplication.UnicodeUTF8))
        self.accelUnits.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Acceleration?configuration=unit", None, QtGui.QApplication.UnicodeUTF8))
        self.decelLabel.setSuffixText(QtGui.QApplication.translate("TaurusMotorV2", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.decelLabel.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Deceleration?configuration=label", None, QtGui.QApplication.UnicodeUTF8))
        self.decelWrite.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Deceleration", None, QtGui.QApplication.UnicodeUTF8))
        self.decelRead.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Deceleration", None, QtGui.QApplication.UnicodeUTF8))
        self.decelUnits.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Deceleration?configuration=unit", None, QtGui.QApplication.UnicodeUTF8))
        self.offsetLabel.setSuffixText(QtGui.QApplication.translate("TaurusMotorV2", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.offsetLabel.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Offset?configuration=label", None, QtGui.QApplication.UnicodeUTF8))
        self.offsetWrite.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.offsetRead.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.offsetUnits.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Offset?configuration=unit", None, QtGui.QApplication.UnicodeUTF8))
        self.baseRateLabel.setSuffixText(QtGui.QApplication.translate("TaurusMotorV2", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.baseRateLabel.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Base_rate?configuration=label", None, QtGui.QApplication.UnicodeUTF8))
        self.baseRateWrite.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Base_rate", None, QtGui.QApplication.UnicodeUTF8))
        self.baseRateRead.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Base_rate", None, QtGui.QApplication.UnicodeUTF8))
        self.baseRateUnits.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Base_rate?configuration=unit", None, QtGui.QApplication.UnicodeUTF8))
        self.stepsUnitLabel.setSuffixText(QtGui.QApplication.translate("TaurusMotorV2", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.stepsUnitLabel.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Step_per_unit?configuration=label", None, QtGui.QApplication.UnicodeUTF8))
        self.stepsUnitsWrite.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Step_per_unit", None, QtGui.QApplication.UnicodeUTF8))
        self.stepsUnitRead.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Step_per_unit", None, QtGui.QApplication.UnicodeUTF8))
        self.stepsUnitUnits.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Step_per_unit?configuration=unit", None, QtGui.QApplication.UnicodeUTF8))
        self.backlashLabel.setSuffixText(QtGui.QApplication.translate("TaurusMotorV2", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.backlashLabel.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Backlash?configuration=label", None, QtGui.QApplication.UnicodeUTF8))
        self.backlashWrite.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Backlash", None, QtGui.QApplication.UnicodeUTF8))
        self.backlashRead.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Backlash", None, QtGui.QApplication.UnicodeUTF8))
        self.backlashUnits.setModel(QtGui.QApplication.translate("TaurusMotorV2", "/Backlash?configuration=unit", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusBoolLed, TaurusConfigLabel, TaurusStateLed, TaurusValueLabel
from taurus.qt.qtgui.container import TaurusGroupBox
from taurus.qt.qtgui.input import TaurusValueLineEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TaurusMotorV2 = QtGui.QDialog()
    ui = Ui_TaurusMotorV2()
    ui.setupUi(TaurusMotorV2)
    TaurusMotorV2.show()
    sys.exit(app.exec_())

