#!/usr/bin/env python

import sys
import mntgrp_gui

from PyQt4 import Qt
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.extra_sardana.measurementgroup import MntGrpChannelPanel
from functools import partial

def openCfgMg(mg):
    d = Qt.QDialog(panel)
    l = Qt.QVBoxLayout()
    d.setLayout(l)
    w = MntGrpChannelPanel(d)
    l.addWidget(w)
    w.setModel(mg)
    d.show()

app = TaurusApplication()

panel = Qt.QMainWindow()
w = Qt.QWidget()
panel.setCentralWidget(w)
ui = mntgrp_gui.Ui_Form()
ui.setupUi(w)


Qt.QObject.connect(ui.cfgMg1, Qt.SIGNAL("clicked()"), partial(openCfgMg, "mg1"))
Qt.QObject.connect(ui.cfgMg2, Qt.SIGNAL("clicked()"), partial(openCfgMg, "mg2"))


panel.show()
sys.exit(app.exec_())
