/*
 * EmptyPanel.java
 *
 * Created on June 7, 2006, 12:43 PM
 */

package es.cells.sardana.client.framework.gui.panel;

/**
 *
 * @author  tcoutinho
 */
public class EmptyPanel extends javax.swing.JPanel {
    
    /** Creates new form EmptyPanel */
    public EmptyPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        nothingLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        nothingLabel.setFont(new java.awt.Font("Arial", 0, 18));
        nothingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nothingLabel.setText("No component selected");
        nothingLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(nothingLabel, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nothingLabel;
    // End of variables declaration//GEN-END:variables
    
}
