/*
 * MotorListPanel.java
 *
 * Created on June 7, 2006, 9:41 AM
 */

package es.cells.sardana.client.framework.gui.panel;

import java.util.Collection;

import javax.swing.table.DefaultTableModel;

import es.cells.sardana.client.framework.pool.Motor;

/**
 *
 * @author  tcoutinho
 */
public class MotorListPanel extends javax.swing.JPanel {
    
    /** Creates new form MotorListPanel */
    public MotorListPanel() {
        initComponents();
    }

    
    public void updateMotorList(Collection<Motor> motors)
    {
    	int rowCount = motorTable.getRowCount();
        for(int i = 0 ; i < rowCount; i++)
        {
        	((DefaultTableModel)motorTable.getModel()).removeRow(0);
        }

        if(motors == null)
                return;

        DefaultTableModel model = (DefaultTableModel) motorTable.getModel();

        for(Motor motor : motors)
        {
                model.addRow(new String[] 
                      { motor.getName(),
                        motor.isAvailable() ? "yes" : "no",
                                motor.getName(),
                                motor.getState(),
                                motor.getDeviceName(),
                                "" + motor.getIdInController()
                      });
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        scrollPane = new javax.swing.JScrollPane();
        motorTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        motorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Available", "Name", "State", "Device Name", "Number in Ctrl"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        motorTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        scrollPane.setViewportView(motorTable);

        add(scrollPane, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable motorTable;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
    
}
