# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/tmpYoLx4X.ui'
#
# Created: Thu Feb 16 17:46:00 2012
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ExpDescriptionEditor(object):
    def setupUi(self, ExpDescriptionEditor):
        ExpDescriptionEditor.setObjectName("ExpDescriptionEditor")
        ExpDescriptionEditor.resize(733, 411)
        self.verticalLayout_3 = QtGui.QVBoxLayout(ExpDescriptionEditor)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtGui.QTabWidget(ExpDescriptionEditor)
        self.tabWidget.setObjectName("tabWidget")
        self.mntGrpTab = QtGui.QWidget()
        self.mntGrpTab.setObjectName("mntGrpTab")
        self.verticalLayout = QtGui.QVBoxLayout(self.mntGrpTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.mntGrpTab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.activeMntGrpCB = QtGui.QComboBox(self.mntGrpTab)
        self.activeMntGrpCB.setObjectName("activeMntGrpCB")
        self.horizontalLayout.addWidget(self.activeMntGrpCB)
        self.mntGrpOptionBT = QtGui.QToolButton(self.mntGrpTab)
        self.mntGrpOptionBT.setObjectName("mntGrpOptionBT")
        self.horizontalLayout.addWidget(self.mntGrpOptionBT)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.channelEditor = MntGrpChannelEditor(self.mntGrpTab)
        self.channelEditor.setObjectName("channelEditor")
        self.verticalLayout.addWidget(self.channelEditor)
        self.tabWidget.addTab(self.mntGrpTab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter = QtGui.QSplitter(self.tab_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tabWidget_2 = QtGui.QTabWidget(self.splitter)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sardanaElementTree = SardanaElementTreeWidget(self.tab_4)
        self.sardanaElementTree.setObjectName("sardanaElementTree")
        self.verticalLayout_5.addWidget(self.sardanaElementTree)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.taurusModelTree = TaurusModelSelectorTree(self.tab)
        self.taurusModelTree.setObjectName("taurusModelTree")
        self.verticalLayout_4.addWidget(self.taurusModelTree)
        self.tabWidget_2.addTab(self.tab, "")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.preScanList = TaurusModelList(self.layoutWidget)
        self.preScanList.setObjectName("preScanList")
        self.verticalLayout_2.addWidget(self.preScanList)
        self.verticalLayout_6.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtGui.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtGui.QSpacerItem(20, 246, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 2)
        self.filenameLE = QtGui.QLineEdit(self.tab_3)
        self.filenameLE.setObjectName("filenameLE")
        self.gridLayout.addWidget(self.filenameLE, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.pathLE = QtGui.QLineEdit(self.tab_3)
        self.pathLE.setObjectName("pathLE")
        self.gridLayout.addWidget(self.pathLE, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 2)
        self.compressionCB = QtGui.QComboBox(self.tab_3)
        self.compressionCB.setObjectName("compressionCB")
        self.compressionCB.addItem(QtCore.QString())
        self.compressionCB.addItem(QtCore.QString())
        self.compressionCB.addItem(QtCore.QString())
        self.compressionCB.addItem(QtCore.QString())
        self.compressionCB.addItem(QtCore.QString())
        self.gridLayout.addWidget(self.compressionCB, 3, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 245, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(ExpDescriptionEditor)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.NoButton)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(ExpDescriptionEditor)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ExpDescriptionEditor)

    def retranslateUi(self, ExpDescriptionEditor):
        ExpDescriptionEditor.setWindowTitle(QtGui.QApplication.translate("ExpDescriptionEditor", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ExpDescriptionEditor", "Active Measurement Group", None, QtGui.QApplication.UnicodeUTF8))
        self.mntGrpOptionBT.setText(QtGui.QApplication.translate("ExpDescriptionEditor", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mntGrpTab), QtGui.QApplication.translate("ExpDescriptionEditor", "Measurement Group", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QtGui.QApplication.translate("ExpDescriptionEditor", "Sardana Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), QtGui.QApplication.translate("ExpDescriptionEditor", "External (Tango)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ExpDescriptionEditor", "(Drag elements from the above selectors and drop them at the bottom list)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("ExpDescriptionEditor", "Snapshot Group", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ExpDescriptionEditor", "File Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ExpDescriptionEditor", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ExpDescriptionEditor", "Data compression", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionCB.setItemText(0, QtGui.QApplication.translate("ExpDescriptionEditor", "nowhere", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionCB.setItemText(1, QtGui.QApplication.translate("ExpDescriptionEditor", "for all datasets", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionCB.setItemText(2, QtGui.QApplication.translate("ExpDescriptionEditor", "for datasets of rank 1 or more", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionCB.setItemText(3, QtGui.QApplication.translate("ExpDescriptionEditor", "for datasets of rank 2 or more", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionCB.setItemText(4, QtGui.QApplication.translate("ExpDescriptionEditor", "for datasets of rank 3 or more", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("ExpDescriptionEditor", "Storage", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.panel import TaurusModelList, TaurusModelSelectorTree
from taurus.qt.qtgui.extra_sardana import SardanaElementTreeWidget, MntGrpChannelEditor
