# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/tmpQAgACn.ui'
#
# Created: Wed Nov 30 11:35:28 2011
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_TaurusConfigurationPanel(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(422, 401)
        self._Form=Form
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayoutRight = QtGui.QGridLayout()
        self.gridLayoutRight.setObjectName("gridLayoutRight")
        self.valueGroupBox = TaurusGroupBox(Form)
        self.valueGroupBox.setFlat(False)
        self.valueGroupBox.setCheckable(False)
        self.valueGroupBox.setObjectName("valueGroupBox")
        self.formLayout_2 = QtGui.QFormLayout(self.valueGroupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.rangeMinLabel = QtGui.QLabel(self.valueGroupBox)
        self.rangeMinLabel.setObjectName("rangeMinLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.rangeMinLabel)
        self.valueMinConfig = TaurusConfigLineEdit(self.valueGroupBox)
        self.valueMinConfig.setObjectName("valueMinConfig")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.valueMinConfig)
        self.rangeMaxLabel = QtGui.QLabel(self.valueGroupBox)
        self.rangeMaxLabel.setObjectName("rangeMaxLabel")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.rangeMaxLabel)
        self.valueMaxConfig = TaurusConfigLineEdit(self.valueGroupBox)
        self.valueMaxConfig.setObjectName("valueMaxConfig")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.valueMaxConfig)
        self.gridLayoutRight.addWidget(self.valueGroupBox, 0, 0, 1, 1)
        self.alarmGroupBox = TaurusGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alarmGroupBox.sizePolicy().hasHeightForWidth())
        self.alarmGroupBox.setSizePolicy(sizePolicy)
        self.alarmGroupBox.setObjectName("alarmGroupBox")
        self.formLayout_3 = QtGui.QFormLayout(self.alarmGroupBox)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.alarmMinLabel = QtGui.QLabel(self.alarmGroupBox)
        self.alarmMinLabel.setObjectName("alarmMinLabel")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.alarmMinLabel)
        self.alarmMinConfig = TaurusConfigLineEdit(self.alarmGroupBox)
        self.alarmMinConfig.setObjectName("alarmMinConfig")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.alarmMinConfig)
        self.alarmMaxLabel = QtGui.QLabel(self.alarmGroupBox)
        self.alarmMaxLabel.setObjectName("alarmMaxLabel")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.alarmMaxLabel)
        self.alarmMaxConfig = TaurusConfigLineEdit(self.alarmGroupBox)
        self.alarmMaxConfig.setObjectName("alarmMaxConfig")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.alarmMaxConfig)
        self.gridLayoutRight.addWidget(self.alarmGroupBox, 1, 0, 1, 1)
        self.warningGroupBox = TaurusGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warningGroupBox.sizePolicy().hasHeightForWidth())
        self.warningGroupBox.setSizePolicy(sizePolicy)
        self.warningGroupBox.setObjectName("warningGroupBox")
        self.formLayout_4 = QtGui.QFormLayout(self.warningGroupBox)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.warningMinLabel = QtGui.QLabel(self.warningGroupBox)
        self.warningMinLabel.setObjectName("warningMinLabel")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.warningMinLabel)
        self.warningMinConfig = TaurusConfigLineEdit(self.warningGroupBox)
        self.warningMinConfig.setObjectName("warningMinConfig")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.warningMinConfig)
        self.warningMaxLabel = QtGui.QLabel(self.warningGroupBox)
        self.warningMaxLabel.setObjectName("warningMaxLabel")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.warningMaxLabel)
        self.warningMaxConfig = TaurusConfigLineEdit(self.warningGroupBox)
        self.warningMaxConfig.setObjectName("warningMaxConfig")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.warningMaxConfig)
        self.gridLayoutRight.addWidget(self.warningGroupBox, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayoutRight.addItem(spacerItem, 3, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayoutRight, 1, 3, 9, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonApply = QtGui.QPushButton(Form)
        self.pushButtonApply.setObjectName("pushButtonApply")
        self.gridLayout_2.addWidget(self.pushButtonApply, 2, 3, 1, 1)
        self.pushButtonCancel = QtGui.QPushButton(Form)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout_2.addWidget(self.pushButtonCancel, 2, 5, 1, 1)
        self.pushButtonRestore = QtGui.QPushButton(Form)
        self.pushButtonRestore.setObjectName("pushButtonRestore")
        self.gridLayout_2.addWidget(self.pushButtonRestore, 2, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(113, 23, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 1)
        self.pushButtonOk = QtGui.QPushButton(Form)
        self.pushButtonOk.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOk.sizePolicy().hasHeightForWidth())
        self.pushButtonOk.setSizePolicy(sizePolicy)
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.gridLayout_2.addWidget(self.pushButtonOk, 2, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 11, 0, 1, 4)
        self.nameLabel = QtGui.QLabel(Form)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.fullNameLineEdit = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.fullNameLineEdit.setFont(font)
        self.fullNameLineEdit.setReadOnly(True)
        self.fullNameLineEdit.setObjectName("fullNameLineEdit")
        self.gridLayout.addWidget(self.fullNameLineEdit, 0, 1, 1, 3)
        self.labelLabel = QtGui.QLabel(Form)
        self.labelLabel.setObjectName("labelLabel")
        self.gridLayout.addWidget(self.labelLabel, 2, 0, 1, 1)
        self.labelConfig = TaurusConfigLineEdit(Form)
        self.labelConfig.setObjectName("labelConfig")
        self.gridLayout.addWidget(self.labelConfig, 2, 1, 1, 2)
        self.unitLabel = QtGui.QLabel(Form)
        self.unitLabel.setObjectName("unitLabel")
        self.gridLayout.addWidget(self.unitLabel, 3, 0, 1, 1)
        self.unitConfig = TaurusConfigLineEdit(Form)
        self.unitConfig.setObjectName("unitConfig")
        self.gridLayout.addWidget(self.unitConfig, 3, 1, 1, 2)
        self.displayUnitLabel = QtGui.QLabel(Form)
        self.displayUnitLabel.setObjectName("displayUnitLabel")
        self.gridLayout.addWidget(self.displayUnitLabel, 4, 0, 1, 1)
        self.displayUnitConfig = TaurusConfigLineEdit(Form)
        self.displayUnitConfig.setObjectName("displayUnitConfig")
        self.gridLayout.addWidget(self.displayUnitConfig, 4, 1, 1, 2)
        self.standardUnitLabel = QtGui.QLabel(Form)
        self.standardUnitLabel.setObjectName("standardUnitLabel")
        self.gridLayout.addWidget(self.standardUnitLabel, 5, 0, 1, 1)
        self.standardUnitConfig = TaurusConfigLineEdit(Form)
        self.standardUnitConfig.setObjectName("standardUnitConfig")
        self.gridLayout.addWidget(self.standardUnitConfig, 5, 1, 1, 2)
        self.formatLabel = QtGui.QLabel(Form)
        self.formatLabel.setObjectName("formatLabel")
        self.gridLayout.addWidget(self.formatLabel, 6, 0, 1, 1)
        self.formatConfig = TaurusConfigLineEdit(Form)
        self.formatConfig.setObjectName("formatConfig")
        self.gridLayout.addWidget(self.formatConfig, 6, 1, 1, 2)
        self.descriptionLabel = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptionLabel.sizePolicy().hasHeightForWidth())
        self.descriptionLabel.setSizePolicy(sizePolicy)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.gridLayout.addWidget(self.descriptionLabel, 7, 0, 1, 2)
        self.descriptionConfig = TaurusConfigLineEdit(Form)
        self.descriptionConfig.setObjectName("descriptionConfig")
        self.gridLayout.addWidget(self.descriptionConfig, 8, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 12, 0, 1, 4)
        spacerItem3 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 9, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "TaurusConfigurationPanel", None, QtGui.QApplication.UnicodeUTF8))
        self.valueGroupBox.setTitle(QtGui.QApplication.translate("Form", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.rangeMinLabel.setText(QtGui.QApplication.translate("Form", "Min:", None, QtGui.QApplication.UnicodeUTF8))
        self.rangeMaxLabel.setText(QtGui.QApplication.translate("Form", "Max:", None, QtGui.QApplication.UnicodeUTF8))
        self.alarmGroupBox.setTitle(QtGui.QApplication.translate("Form", "Alarm", None, QtGui.QApplication.UnicodeUTF8))
        self.alarmMinLabel.setText(QtGui.QApplication.translate("Form", "Min:", None, QtGui.QApplication.UnicodeUTF8))
        self.alarmMaxLabel.setText(QtGui.QApplication.translate("Form", "Max:", None, QtGui.QApplication.UnicodeUTF8))
        self.warningGroupBox.setTitle(QtGui.QApplication.translate("Form", "Warning", None, QtGui.QApplication.UnicodeUTF8))
        self.warningMinLabel.setText(QtGui.QApplication.translate("Form", "Min:", None, QtGui.QApplication.UnicodeUTF8))
        self.warningMaxLabel.setText(QtGui.QApplication.translate("Form", "Max:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonApply.setText(QtGui.QApplication.translate("Form", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("Form", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRestore.setText(QtGui.QApplication.translate("Form", "Restore", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOk.setText(QtGui.QApplication.translate("Form", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLabel.setText(QtGui.QApplication.translate("Form", "Full Name", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLabel.setText(QtGui.QApplication.translate("Form", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.unitLabel.setText(QtGui.QApplication.translate("Form", "Unit:", None, QtGui.QApplication.UnicodeUTF8))
        self.displayUnitLabel.setText(QtGui.QApplication.translate("Form", "Display Unit:", None, QtGui.QApplication.UnicodeUTF8))
        self.standardUnitLabel.setText(QtGui.QApplication.translate("Form", "Standard Unit:", None, QtGui.QApplication.UnicodeUTF8))
        self.formatLabel.setText(QtGui.QApplication.translate("Form", "Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.descriptionLabel.setText(QtGui.QApplication.translate("Form", "Description:", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.container import TaurusGroupBox
from taurus.qt.qtgui.input import TaurusConfigLineEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

