//+=============================================================================
//
// file :         OneDExpChannelStateMachine.cpp
//
// description :  C++ source for the OneDExpChannel and its alowed. 
//                method for commands and attributes
//
// project :      TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
//
// $Log:  $
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#include "OneDExpChannel.h"
#include "OneDExpChannelClass.h"
#include <tango.h>

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace OneDExpChannel_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		OneDExpChannel::is_DataLength_allowed
// 
// description : 	Read/Write allowed for DataLength attribute.
//
//-----------------------------------------------------------------------------
bool OneDExpChannel::is_DataLength_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		OneDExpChannel::is_Data_allowed
// 
// description : 	Read/Write allowed for Data attribute.
//
//-----------------------------------------------------------------------------
bool OneDExpChannel::is_Data_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		OneDExpChannel::is_Value_allowed
// 
// description : 	Read/Write allowed for Value attribute.
//
//-----------------------------------------------------------------------------
bool OneDExpChannel::is_Value_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		OneDExpChannel::is_Start_allowed
// 
// description : 	Execution allowed for Start command.
//
//-----------------------------------------------------------------------------
bool OneDExpChannel::is_Start_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		OneDExpChannel::is_Abort_allowed
// 
// description : 	Execution allowed for Abort command.
//
//-----------------------------------------------------------------------------
bool OneDExpChannel::is_Abort_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

}	// namespace OneDExpChannel_ns
