static const char *RcsId = "$Header:  $";
//+=============================================================================
//
// file :         ControllerStateMachine.cpp
//
// description :  C++ source for the Controller and its alowed. 
//                method for commands and attributes
//
// project :      TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
//
// $Log:  $
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#include <tango.h>
#include <Controller.h>
#include <ControllerClass.h>

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace Controller_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		Controller::is_Elements_allowed
// 
// description : 	Read/Write allowed for Elements attribute.
//
//-----------------------------------------------------------------------------
bool Controller::is_Elements_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		Controller::is_AddElement_allowed
// 
// description : 	Execution allowed for AddElement command.
//
//-----------------------------------------------------------------------------
bool Controller::is_AddElement_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Controller::is_DeleteElement_allowed
// 
// description : 	Execution allowed for DeleteElement command.
//
//-----------------------------------------------------------------------------
bool Controller::is_DeleteElement_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Controller::is_Send_allowed
// 
// description : 	Execution allowed for Send command.
//
//-----------------------------------------------------------------------------
bool Controller::is_Send_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

}	// namespace Controller_ns
