# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/tmpgrv08D.ui'
#
# Created: Tue May 15 10:29:42 2012
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DoubleListDlg(object):
    def setupUi(self, DoubleListDlg):
        DoubleListDlg.setObjectName("DoubleListDlg")
        DoubleListDlg.resize(533, 426)
        DoubleListDlg.setModal(True)
        self.verticalLayout_4 = QtGui.QVBoxLayout(DoubleListDlg)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mainLabel = QtGui.QLabel(DoubleListDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainLabel.sizePolicy().hasHeightForWidth())
        self.mainLabel.setSizePolicy(sizePolicy)
        self.mainLabel.setWordWrap(True)
        self.mainLabel.setMargin(6)
        self.mainLabel.setObjectName("mainLabel")
        self.verticalLayout_4.addWidget(self.mainLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.group1 = QtGui.QGroupBox(DoubleListDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group1.sizePolicy().hasHeightForWidth())
        self.group1.setSizePolicy(sizePolicy)
        self.group1.setObjectName("group1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.group1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.list1 = QtGui.QListWidget(self.group1)
        self.list1.setDragEnabled(True)
        self.list1.setDragDropOverwriteMode(True)
        self.list1.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.list1.setAlternatingRowColors(True)
        self.list1.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.list1.setObjectName("list1")
        self.verticalLayout_2.addWidget(self.list1)
        self.horizontalLayout.addWidget(self.group1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.to2BT = QtGui.QToolButton(DoubleListDlg)
        self.to2BT.setArrowType(QtCore.Qt.RightArrow)
        self.to2BT.setObjectName("to2BT")
        self.verticalLayout_3.addWidget(self.to2BT)
        self.to1BT = QtGui.QToolButton(DoubleListDlg)
        self.to1BT.setArrowType(QtCore.Qt.LeftArrow)
        self.to1BT.setObjectName("to1BT")
        self.verticalLayout_3.addWidget(self.to1BT)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.group2 = QtGui.QGroupBox(DoubleListDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group2.sizePolicy().hasHeightForWidth())
        self.group2.setSizePolicy(sizePolicy)
        self.group2.setObjectName("group2")
        self.verticalLayout = QtGui.QVBoxLayout(self.group2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.list2 = QtGui.QListWidget(self.group2)
        self.list2.setDragEnabled(True)
        self.list2.setDragDropOverwriteMode(True)
        self.list2.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.list2.setAlternatingRowColors(True)
        self.list2.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.list2.setObjectName("list2")
        self.verticalLayout.addWidget(self.list2)
        self.horizontalLayout.addWidget(self.group2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.buttonBox = QtGui.QDialogButtonBox(DoubleListDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(DoubleListDlg)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), DoubleListDlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), DoubleListDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(DoubleListDlg)

    def retranslateUi(self, DoubleListDlg):
        self.list1.setSortingEnabled(True)
        self.to2BT.setText(QtGui.QApplication.translate("DoubleListDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.to1BT.setText(QtGui.QApplication.translate("DoubleListDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.list2.setSortingEnabled(True)

