static const char *RcsId     = "$Header$";
static const char *TagName   = "$Name$";
static const char *HttpServer= "http://www.esrf.fr/computing/cs/tango/tango_doc/ds_doc/";
//+=============================================================================
//
// file :        ZeroDExpChannelClass.cpp
//
// description : C++ source for the ZeroDExpChannelClass. A singleton
//               class derived from DeviceClass. It implements the
//               command list and all properties and methods required
//               by the ZeroDExpChannel once per process.
//
// project :     TANGO Device Server
//
// $Author$
//
// $Revision$
//
// $Log$
// Revision 1.5  2007/07/26 07:05:42  tcoutinho
// fix bug 10 : Change all tango commands from Stop to Abort
//
// Revision 1.4  2007/05/11 08:40:33  tcoutinho
// - fixed bugs
//
// Revision 1.3  2007/05/07 10:14:28  tcoutinho
// - Changed default value of ContinueOnError according to latest sardana meeting
//
// Revision 1.2  2007/02/08 07:56:49  etaurel
// - Changes after compilation -Wall. Added the CumulatedValue attribute and
// everything to implement it (thread....)
//
// Revision 1.1  2007/01/26 08:35:02  etaurel
// - We now have a first release of ZeroDController
//
//
// copyleft :   CELLS/ALBA
//		Edifici Ciences Nord
//		Campus Universitari de Bellaterra
//		Universitat Autonoma de Barcelona
//		08193 Bellaterra, Barcelona, SPAIN
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//=============================================================================

#include <CtrlFiCa.h>
#include <tango.h>

#include <ZeroDExpChannel.h>
#include <ZeroDExpChannelClass.h>


//+----------------------------------------------------------------------------
/**
 *	Create ZeroDExpChannelClass singleton and return it in a C function for Python usage
 */
//+----------------------------------------------------------------------------
extern "C" {
#ifdef WIN32

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_ZeroDExpChannel_class(const char *name) {
		return ZeroDExpChannel_ns::ZeroDExpChannelClass::init(name);
	}
}


namespace ZeroDExpChannel_ns
{
//+----------------------------------------------------------------------------
//
// method : 		AbortCmd::execute()
// 
// description : 	method to trigger the execution of the command.
//                PLEASE DO NOT MODIFY this method core without pogo   
//
// in : - device : The device on which the command must be excuted
//		- in_any : The command input data
//
// returns : The command output data (packed in the Any object)
//
//-----------------------------------------------------------------------------
CORBA::Any *AbortCmd::execute(Tango::DeviceImpl *device,const CORBA::Any &in_any)
{

	cout2 << "AbortCmd::execute(): arrived" << endl;

	((static_cast<ZeroDExpChannel *>(device))->abort());
	return new CORBA::Any();
}


//+----------------------------------------------------------------------------
//
// method : 		StartClass::execute()
// 
// description : 	method to trigger the execution of the command.
//                PLEASE DO NOT MODIFY this method core without pogo   
//
// in : - device : The device on which the command must be excuted
//		- in_any : The command input data
//
// returns : The command output data (packed in the Any object)
//
//-----------------------------------------------------------------------------
CORBA::Any *StartClass::execute(Tango::DeviceImpl *device,const CORBA::Any &in_any)
{

	cout2 << "StartClass::execute(): arrived" << endl;

	((static_cast<ZeroDExpChannel *>(device))->start());
	return new CORBA::Any();
}



//
//----------------------------------------------------------------
//	Initialize pointer for singleton pattern
//----------------------------------------------------------------
//
ZeroDExpChannelClass *ZeroDExpChannelClass::_instance = NULL;

//+----------------------------------------------------------------------------
//
// method : 		ZeroDExpChannelClass::ZeroDExpChannelClass(string &s)
// 
// description : 	constructor for the ZeroDExpChannelClass
//
// in : - s : The class name
//
//-----------------------------------------------------------------------------
ZeroDExpChannelClass::ZeroDExpChannelClass(string &s):DeviceClass(s)
{

	cout2 << "Entering ZeroDExpChannelClass constructor" << endl;
	set_default_property();
	get_class_property();
	write_class_property();
	
	nb_static_attr = 0;
	first_call_to_device_factory = true;
	
	cout2 << "Leaving ZeroDExpChannelClass constructor" << endl;

}
//+----------------------------------------------------------------------------
//
// method : 		ZeroDExpChannelClass::~ZeroDExpChannelClass()
// 
// description : 	destructor for the ZeroDExpChannelClass
//
//-----------------------------------------------------------------------------
ZeroDExpChannelClass::~ZeroDExpChannelClass()
{
	_instance = NULL;
}

//+----------------------------------------------------------------------------
//
// method : 		ZeroDExpChannelClass::instance
// 
// description : 	Create the object if not already done. Otherwise, just
//			return a pointer to the object
//
// in : - name : The class name
//
//-----------------------------------------------------------------------------
ZeroDExpChannelClass *ZeroDExpChannelClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new ZeroDExpChannelClass(s);
		}
		catch (bad_alloc)
		{
			throw;
		}		
	}		
	return _instance;
}

ZeroDExpChannelClass *ZeroDExpChannelClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}

//+----------------------------------------------------------------------------
//
// method : 		ZeroDExpChannelClass::command_factory
// 
// description : 	Create the command object(s) and store them in the 
//			command list
//
//-----------------------------------------------------------------------------
void ZeroDExpChannelClass::command_factory()
{
	command_list.push_back(new StartClass("Start",
		Tango::DEV_VOID, Tango::DEV_VOID,
		"",
		"",
		Tango::OPERATOR));
	command_list.push_back(new AbortCmd("Abort",
		Tango::DEV_VOID, Tango::DEV_VOID,
		"",
		"",
		Tango::OPERATOR));

	//	add polling if any
	for (unsigned int i=0 ; i<command_list.size(); i++)
	{
	}
}

//+----------------------------------------------------------------------------
//
// method : 		ZeroDExpChannelClass::get_class_property
// 
// description : 	Get the class property for specified name.
//
// in :		string	name : The property name
//
//+----------------------------------------------------------------------------
Tango::DbDatum ZeroDExpChannelClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}
//+----------------------------------------------------------------------------
//
// method : 		ZeroDExpChannelClass::get_default_device_property()
// 
// description : 	Return the default value for device property.
//
//-----------------------------------------------------------------------------
Tango::DbDatum ZeroDExpChannelClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//+----------------------------------------------------------------------------
//
// method : 		ZeroDExpChannelClass::get_default_class_property()
// 
// description : 	Return the default value for class property.
//
//-----------------------------------------------------------------------------
Tango::DbDatum ZeroDExpChannelClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}
//+----------------------------------------------------------------------------
//
// method : 		ZeroDExpChannelClass::device_factory
// 
// description : 	Create the device object(s) and store them in the 
//			device list
//
// in :		Tango::DevVarStringArray *devlist_ptr : The device name list
//
//-----------------------------------------------------------------------------
void ZeroDExpChannelClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{

	//	Create all devices.(Automatic code generation)
	//-------------------------------------------------------------
	for (unsigned long i=0 ; i < devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
						
		// Create devices and add it into the device list
		//----------------------------------------------------
		device_list.push_back(new ZeroDExpChannel(this, (*devlist_ptr)[i]));							 

		// Export device to the outside world
		// Check before if database used.
		//---------------------------------------------
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(device_list.back());
		else
			export_device(device_list.back(), (*devlist_ptr)[i]);
	}
	//	End of Automatic code generation
	//-------------------------------------------------------------

	long nb_dev = device_list.size();

//
// Get the number of static attribute before any dynamic one is added
//
	
	if ((nb_dev != 0) && (first_call_to_device_factory == true))
	{
		nb_static_attr = device_list.back()->get_device_attr()->get_attr_nb();
		first_call_to_device_factory = false;
	}

//
// Create dynamic attribute but remove the unwanted ones
//
	
	long nb_new_device = devlist_ptr->length();
	long start_index;
	
	if (nb_dev != 0)
		start_index = nb_dev - nb_new_device;
	else
		start_index = 0;
		
	for (long i=0 ; i < nb_new_device ; i++)
	{
		if (static_cast<ZeroDExpChannel *>(device_list[start_index + i])->is_add_device_done() == true)
		{
			static_cast<ZeroDExpChannel *>(device_list[start_index + i])->create_dyn_attr();
			static_cast<ZeroDExpChannel *>(device_list[start_index + i])->remove_unwanted_dyn_attr_from_device();
		}	
	}	

}
//+----------------------------------------------------------------------------
//	Method: ZeroDExpChannelClass::attribute_factory(vector<Tango::Attr *> &att_list)
//-----------------------------------------------------------------------------
void ZeroDExpChannelClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	//	Attribute : Value
	ValueAttrib	*value = new ValueAttrib();
	att_list.push_back(value);

	//	Attribute : SimulationMode
	SimulationModeAttrib	*simulation_mode = new SimulationModeAttrib();
	att_list.push_back(simulation_mode);

	//	Attribute : Instrument
	InstrumentAttrib	*instrument = new InstrumentAttrib();
	instrument->set_disp_level(Tango::EXPERT);
	att_list.push_back(instrument);

	//	Attribute : CumulationType
	CumulationTypeAttrib	*cumulation_type = new CumulationTypeAttrib();
	cumulation_type->set_memorized();
	cumulation_type->set_memorized_init(true);
	att_list.push_back(cumulation_type);

	//	Attribute : CumulatedValue
	CumulatedValueAttrib	*cumulated_value = new CumulatedValueAttrib();
	att_list.push_back(cumulated_value);

	//	Attribute : CumulatedPointsNumber
	CumulatedPointsNumberAttrib	*cumulated_points_number = new CumulatedPointsNumberAttrib();
	att_list.push_back(cumulated_points_number);

	//	Attribute : CumulatedPointsError
	CumulatedPointsErrorAttrib	*cumulated_points_error = new CumulatedPointsErrorAttrib();
	att_list.push_back(cumulated_points_error);

	//	Attribute : CumulationTime
	CumulationTimeAttrib	*cumulation_time = new CumulationTimeAttrib();
	cumulation_time->set_memorized();
	cumulation_time->set_memorized_init(true);
	att_list.push_back(cumulation_time);

	//	Attribute : ValueBuffer
	ValueBufferAttrib	*value_buffer = new ValueBufferAttrib();
	Tango::UserDefaultAttrProp	value_buffer_prop;
	value_buffer_prop.set_label("Value Buffer");
	value_buffer->set_default_properties(value_buffer_prop);
	att_list.push_back(value_buffer);

	//	Attribute : TimeBuffer
	TimeBufferAttrib	*time_buffer = new TimeBufferAttrib();
	att_list.push_back(time_buffer);

	//	End of Automatic code generation
	//-------------------------------------------------------------
}

//+----------------------------------------------------------------------------
//
// method : 		ZeroDExpChannelClass::get_class_property()
// 
// description : 	Read the class properties from database.
//
//-----------------------------------------------------------------------------
void ZeroDExpChannelClass::get_class_property()
{
	//	Initialize your default values here (if not done with  POGO).
	//------------------------------------------------------------------

	//	Read class properties from database.(Automatic code generation)
	//------------------------------------------------------------------

	//	Call database and extract values
	//--------------------------------------------
	if (Tango::Util::instance()->_UseDb==true)
		get_db_class()->get_property(cl_prop);
	Tango::DbDatum	def_prop;

	//	End of Automatic code generation
	//------------------------------------------------------------------

}

//+----------------------------------------------------------------------------
//
// method : 	ZeroDExpChannelClass::set_default_property
// 
// description: Set default property (class and device) for wizard.
//              For each property, add to wizard property name and description
//              If default value has been set, add it to wizard property and
//              store it in a DbDatum.
//
//-----------------------------------------------------------------------------
void ZeroDExpChannelClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;

	vector<string>	vect_data;
	//	Set Default Class Properties
	//	Set Default Device Properties
	prop_name = "id";
	prop_desc = "The experiment channel identifier";
	prop_def  = "";
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "StopIfNoTime";
	prop_desc = "Stop cumulate data if there is not enough time to get one more point\nbefore the  timer expires";
	prop_def  = "True";
	vect_data.clear();
	vect_data.push_back("True");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "ContinueOnError";
	prop_desc = "Continue cumulating data even if an error occurs during data reading";
	prop_def  = "True";
	vect_data.clear();
	vect_data.push_back("True");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

}
//+----------------------------------------------------------------------------
//
// method : 		ZeroDExpChannelClass::write_class_property
// 
// description : 	Set class description as property in database
//
//-----------------------------------------------------------------------------
void ZeroDExpChannelClass::write_class_property()
{
	//	First time, check if database used
	//--------------------------------------------
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("ZeroDimensionExperimentChannel");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Zero Dimension Experiment device used by the Sardana project device pool");
	description << str_desc;
	data.push_back(description);
		
	//	put cvs location
	string	rcsId(RcsId);
	string	filename(classname);
	start = rcsId.find("/");
	if (start!=string::npos)
	{
		filename += "Class.cpp";
		end   = rcsId.find(filename);
		if (end>start)
		{
			string	strloc = rcsId.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	//	Get CVS tag revision
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("Device_4Impl");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	//--------------------------------------------
	get_db_class()->put_property(data);
}

}	// namespace
