#!/usr/bin/env python

##############################################################################
##
## This file is part of Sardana
##
## http://www.tango-controls.org/static/sardana/latest/doc/html/index.html
##
## Copyright 2011 CELLS / ALBA Synchrotron, Bellaterra, Spain
## 
## Sardana is free software: you can redistribute it and/or modify
## it under the terms of the GNU Lesser General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
## 
## Sardana is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Lesser General Public License for more details.
## 
## You should have received a copy of the GNU Lesser General Public License
## along with Sardana.  If not, see <http://www.gnu.org/licenses/>.
##
##############################################################################

""" """

__all__ = ["main"]

__docformat__ = 'restructuredtext'

import datetime
__START_TIME = datetime.datetime.now()

def set_src():
    import sys
    import os.path as osp
    sar_dir = osp.join(osp.dirname(osp.abspath(__file__)), osp.pardir, 'src')
    sys.path.append(osp.abspath(sar_dir))

try:
    import sardana
except ImportError:
    # try to use code from src distribution
    set_src()
    import sardana

def run():
    import sardana.tango
    sardana.tango.run(start_time=__START_TIME)

def main():
    run()

if __name__ == '__main__':
    main()