#!/usr/bin/env python

##############################################################################
##
## This file is part of Sardana
##
## http://www.tango-controls.org/static/sardana/latest/doc/html/index.html
##
## Copyright 2011 CELLS / ALBA Synchrotron, Bellaterra, Spain
## 
## Sardana is free software: you can redistribute it and/or modify
## it under the terms of the GNU Lesser General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
## 
## Sardana is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Lesser General Public License for more details.
## 
## You should have received a copy of the GNU Lesser General Public License
## along with Sardana.  If not, see <http://www.gnu.org/licenses/>.
##
##############################################################################

"""The Spock startup file. This executable is actually an extension of the 
   ipython file that can be found in <prefix>/ipython (prefix usually being in 
   linux '/usr/bin'"""

__all__ = [ "main" ]

__docformat__ = 'restructuredtext'

def set_src():
    import sys
    import os.path as osp
    sar_dir = osp.join(osp.dirname(osp.abspath(__file__)), osp.pardir, 'src')
    sys.path.append(osp.abspath(sar_dir))

try:
    from sardana.spock import genutils
except ImportError:
    # try to use code from src distribution
    set_src()
    from sardana.spock import genutils
    
def main():
    genutils.run()
    
if __name__ == '__main__':
    main()
