# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaurusPlotConf.ui'
#
# Created: Fri Oct 15 11:43:10 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_TaurusPlotConfDlg(object):
    def setupUi(self, TaurusPlotConfDlg):
        TaurusPlotConfDlg.setObjectName("TaurusPlotConfDlg")
        TaurusPlotConfDlg.resize(844, 564)
        self.verticalLayout_8 = QtGui.QVBoxLayout(TaurusPlotConfDlg)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.splitter = QtGui.QSplitter(TaurusPlotConfDlg)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox_2 = QtGui.QGroupBox(self.splitter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtGui.QTabWidget(self.groupBox_2)
        self.tabWidget.setObjectName("tabWidget")
        self.tangoTab = QtGui.QWidget()
        self.tangoTab.setObjectName("tangoTab")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tangoTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tangoTree = QtGui.QWidget(self.tangoTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tangoTree.sizePolicy().hasHeightForWidth())
        self.tangoTree.setSizePolicy(sizePolicy)
        self.tangoTree.setObjectName("tangoTree")
        self.horizontalLayout.addWidget(self.tangoTree)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tangoSendBT = QtGui.QToolButton(self.tangoTab)
        self.tangoSendBT.setArrowType(QtCore.Qt.RightArrow)
        self.tangoSendBT.setObjectName("tangoSendBT")
        self.verticalLayout.addWidget(self.tangoSendBT)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tangoTab, "")
        self.nexusTab = QtGui.QWidget()
        self.nexusTab.setObjectName("nexusTab")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.nexusTab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.nexusBrowser = QtGui.QLabel(self.nexusTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nexusBrowser.sizePolicy().hasHeightForWidth())
        self.nexusBrowser.setSizePolicy(sizePolicy)
        self.nexusBrowser.setAlignment(QtCore.Qt.AlignCenter)
        self.nexusBrowser.setObjectName("nexusBrowser")
        self.horizontalLayout_5.addWidget(self.nexusBrowser)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.nexusSendBT = QtGui.QToolButton(self.nexusTab)
        self.nexusSendBT.setArrowType(QtCore.Qt.RightArrow)
        self.nexusSendBT.setObjectName("nexusSendBT")
        self.verticalLayout_2.addWidget(self.nexusSendBT)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.nexusTab, "")
        self.asciiTab = QtGui.QWidget()
        self.asciiTab.setObjectName("asciiTab")
        self.layoutWidget_2 = QtGui.QWidget(self.asciiTab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(350, 0, 34, 459))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolButton_3 = QtGui.QToolButton(self.layoutWidget_2)
        self.toolButton_3.setObjectName("toolButton_3")
        self.verticalLayout_3.addWidget(self.toolButton_3)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.tabWidget.addTab(self.asciiTab, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.groupBox_3 = QtGui.QGroupBox(self.splitter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.curvesTable = QtGui.QTableView(self.groupBox_3)
        self.curvesTable.setDragEnabled(True)
        self.curvesTable.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.curvesTable.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.curvesTable.setObjectName("curvesTable")
        self.verticalLayout_4.addWidget(self.curvesTable)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.visibilityBT = QtGui.QToolButton(self.groupBox_3)
        self.visibilityBT.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.visibilityBT.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.visibilityBT.setObjectName("visibilityBT")
        self.horizontalLayout_2.addWidget(self.visibilityBT)
        self.removeCurvesBT = QtGui.QToolButton(self.groupBox_3)
        self.removeCurvesBT.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.removeCurvesBT.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.removeCurvesBT.setObjectName("removeCurvesBT")
        self.horizontalLayout_2.addWidget(self.removeCurvesBT)
        self.editCurvesTableBT = QtGui.QToolButton(self.groupBox_3)
        self.editCurvesTableBT.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.editCurvesTableBT.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.editCurvesTableBT.setObjectName("editCurvesTableBT")
        self.horizontalLayout_2.addWidget(self.editCurvesTableBT)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.groupBox = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.propView = QtGui.QWidget(self.groupBox)
        self.propView.setObjectName("propView")
        self.horizontalLayout_4.addWidget(self.propView)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.bckgndBT = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bckgndBT.sizePolicy().hasHeightForWidth())
        self.bckgndBT.setSizePolicy(sizePolicy)
        self.bckgndBT.setObjectName("bckgndBT")
        self.verticalLayout_6.addWidget(self.bckgndBT)
        self.gridColorBT = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridColorBT.sizePolicy().hasHeightForWidth())
        self.gridColorBT.setSizePolicy(sizePolicy)
        self.gridColorBT.setObjectName("gridColorBT")
        self.verticalLayout_6.addWidget(self.gridColorBT)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.verticalLayout_8.addWidget(self.splitter)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.reloadBT = QtGui.QPushButton(TaurusPlotConfDlg)
        self.reloadBT.setObjectName("reloadBT")
        self.horizontalLayout_3.addWidget(self.reloadBT)
        self.cancelBT = QtGui.QPushButton(TaurusPlotConfDlg)
        self.cancelBT.setObjectName("cancelBT")
        self.horizontalLayout_3.addWidget(self.cancelBT)
        self.applyBT = QtGui.QPushButton(TaurusPlotConfDlg)
        self.applyBT.setObjectName("applyBT")
        self.horizontalLayout_3.addWidget(self.applyBT)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)

        self.retranslateUi(TaurusPlotConfDlg)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TaurusPlotConfDlg)

    def retranslateUi(self, TaurusPlotConfDlg):
        TaurusPlotConfDlg.setWindowTitle(QtGui.QApplication.translate("TaurusPlotConfDlg", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("TaurusPlotConfDlg", "Sources of data", None, QtGui.QApplication.UnicodeUTF8))
        self.tangoSendBT.setText(QtGui.QApplication.translate("TaurusPlotConfDlg", "->", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tangoTab), QtGui.QApplication.translate("TaurusPlotConfDlg", "Tango", None, QtGui.QApplication.UnicodeUTF8))
        self.nexusBrowser.setText(QtGui.QApplication.translate("TaurusPlotConfDlg", "Nexus browsing not available. ", None, QtGui.QApplication.UnicodeUTF8))
        self.nexusSendBT.setText(QtGui.QApplication.translate("TaurusPlotConfDlg", "->", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.nexusTab), QtGui.QApplication.translate("TaurusPlotConfDlg", "Nexus", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_3.setText(QtGui.QApplication.translate("TaurusPlotConfDlg", "->", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.asciiTab), QtGui.QApplication.translate("TaurusPlotConfDlg", "ASCII", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("TaurusPlotConfDlg", "Contents & appearance", None, QtGui.QApplication.UnicodeUTF8))
        self.visibilityBT.setText(QtGui.QApplication.translate("TaurusPlotConfDlg", "Visibility...", None, QtGui.QApplication.UnicodeUTF8))
        self.removeCurvesBT.setText(QtGui.QApplication.translate("TaurusPlotConfDlg", " Remove...", None, QtGui.QApplication.UnicodeUTF8))
        self.editCurvesTableBT.setText(QtGui.QApplication.translate("TaurusPlotConfDlg", "Edit...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("TaurusPlotConfDlg", "Appearance of selected curves", None, QtGui.QApplication.UnicodeUTF8))
        self.bckgndBT.setText(QtGui.QApplication.translate("TaurusPlotConfDlg", "Canvas Color...", None, QtGui.QApplication.UnicodeUTF8))
        self.gridColorBT.setText(QtGui.QApplication.translate("TaurusPlotConfDlg", "Grid Color...", None, QtGui.QApplication.UnicodeUTF8))
        self.reloadBT.setText(QtGui.QApplication.translate("TaurusPlotConfDlg", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelBT.setText(QtGui.QApplication.translate("TaurusPlotConfDlg", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.applyBT.setText(QtGui.QApplication.translate("TaurusPlotConfDlg", "Apply", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TaurusPlotConfDlg = QtGui.QWidget()
    ui = Ui_TaurusPlotConfDlg()
    ui.setupUi(TaurusPlotConfDlg)
    TaurusPlotConfDlg.show()
    sys.exit(app.exec_())

