//+=============================================================================
//
// file :         TwoDExpChannel.cpp
//
// description :  C++ source for the TwoDExpChannel and its commands. 
//                The class is derived from Device. It represents the
//                CORBA servant object which will be accessed from the
//                network. All commands which can be executed on the
//                TwoDExpChannel are implemented in this file.
//
// project :      TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
//
// $Log:  $
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================



//===================================================================
//
//	The following table gives the correspondance
//	between commands and method's name.
//
//  Command's name|  Method's name
//	----------------------------------------
//  State   |  dev_state()
//  Status  |  dev_status()
//  Start   |  start()
//  Abort   |  abort()
//
//===================================================================


#include "CtrlFiCa.h"
#include <tango.h>
#include "TwoDExpChannel.h"
#include "TwoDExpChannelClass.h"
#include "Pool.h"
#include "PoolUtil.h"
#include "TwoDExpChannelUtil.h"
#include "TwoDThread.h"
#include "MeasurementGroup.h"

#include <pool/TwoDCtrl.h>

#include <numeric>

namespace TwoDExpChannel_ns
{

//+----------------------------------------------------------------------------
//
// method : 		TwoDExpChannel::TwoDExpChannel(string &s)
// 
// description : 	constructor for simulated TwoDExpChannel
//
// in : - cl : Pointer to the DeviceClass object
//      - s : Device name 
//
//-----------------------------------------------------------------------------
TwoDExpChannel::TwoDExpChannel(Tango::DeviceClass *cl,string &s)
:Pool_ns::PoolIndBaseDev(cl,s.c_str())
{
    init_cmd = false; 
    init_device();
}

TwoDExpChannel::TwoDExpChannel(Tango::DeviceClass *cl,const char *s)
:Pool_ns::PoolIndBaseDev(cl,s)
{
    init_cmd = false;
    init_device();
}

TwoDExpChannel::TwoDExpChannel(Tango::DeviceClass *cl,const char *s,const char *d)
:Pool_ns::PoolIndBaseDev(cl,s,d)
{
    init_cmd = false;
    init_device();
}
//+----------------------------------------------------------------------------
//
// method : 		TwoDExpChannel::delete_device()
// 
// description : 	will be called at device destruction or at init command.
//
//-----------------------------------------------------------------------------
void TwoDExpChannel::delete_device()
{
    INFO_STREAM << "TwoDExpChannel::delete_device() " << device_name << endl;
    
//	Delete device's allocated object

    if (attr_Value_read) {
        delete[] attr_Value_read;
        attr_Value_read = 0;
    }
    

//
// To know that we are executing this code due to a pool shutdown and not due to a
// "Init" command, we are using the polling thread ptr which is cleared in the DS
// shutdown sequence before the device destruction
//
    bool sd = false;


    Tango::Util *tg = Tango::Util::instance();
    if (tg->get_polling_thread_object() != NULL)
    {
        if (get_state() == Tango::MOVING)
        {
            TangoSys_OMemStream o;
            o << "Init command on 2D channel device is not allowed while a 2D channel is counting" << ends;

            Tango::Except::throw_exception((const char *)"TwoDExp_InitNotAllowed",o.str(),
                    (const char *)"TwoDExpChannel::delete_device");
        }
    }
    else
    {
        sd = true;
    }

    if (save_atts != NULL)
        delete save_atts;

//
// If we are not in a shutdown sequence:
// Lock the ghost group in order the polling thread not to
// start requesting for motor state while we are deleting it and
// inform ghost group that there is one channel less
//
// If we are called due to a Init command on the DServer admin,
// the measurement_group class is already deleted and the ghost group
// as well
//

    if (sd == false)
    {
        bool measurementgroup_class_deleted = false;
        MeasurementGroup_ns::MeasurementGroup *ghost_ptr;
        
        try
        {
            ghost_ptr = pool_dev->get_ghost_measurement_group_ptr();
        }
        catch (Tango::DevFailed &e)
        {
            measurementgroup_class_deleted = true;
        }
        
        if (measurementgroup_class_deleted == false)
        {
            Tango::AutoTangoMonitor atm(ghost_ptr);
            ghost_ptr->remove_channel_from_ghost_group(get_id());
        }
    }
                
//
// Delete the device from its controller and from the pool
//
  
    // If in shutdown mode, protect against exceptions
    if (sd)
    {
        try
        {
            delete_from_pool();
        }
        catch(Tango::DevFailed &df)
        {
            std::cout << "Error deleting '"<< get_name()
                      << "' from controller:" << std::endl;
            Tango::Except::print_exception(df);
        }
        catch(...)
        {
            std::cout << "Unknown error deleting '"<< get_name()
                      << "' from controller." << std::endl;
        }        
    }
    else
    {
        delete_from_pool();
    }
    delete_utils();
    
    PoolIndBaseDev::delete_device();
}

//+----------------------------------------------------------------------------
//
// method : 		TwoDExpChannel::init_device()
// 
// description : 	will be called at device initialization.
//
//-----------------------------------------------------------------------------
void TwoDExpChannel::init_device()
{
    INFO_STREAM << "TwoDExpChannel::TwoDExpChannel() create device " << device_name << endl;

    // Initialise variables to default values
    //--------------------------------------------


    PoolIndBaseDev::init_device();


//
// Init some variables
//

    save_atts = NULL;
//	read_value  = 0.0;
//	cum_read_value = 0.0;
//	cum_nb = 0;
//	cum_err = 0;
    th = NULL;

    
//	if (init_cmd == false)
//	{
//	attr_CumulationType_write = Pool_ns::AVERAGE;
//		attr_CumulationTime_write = 0.0;
//	}
    
//	Tango::WAttribute &acq_att = dev_attr->get_w_attr_by_name("CumulationType");
//	acq_att.set_write_value((long)Pool_ns::AVERAGE);
        
    if(maxXDim < 1) maxXDim = 2000;
    if(maxYDim < 1) maxYDim = 2000;
    
    attr_Value_read = new Tango::DevDouble[maxXDim * maxYDim];
    
    ::memset(attr_Value_read, 0, maxXDim * maxYDim * sizeof(Tango::DevDouble));
    
    
    attr_XDim_write = maxXDim;
    attr_YDim_write = maxYDim;


    
//	the_shared_data.error_nb = 0;
//	the_shared_data.cont_error = continueOnError;
//	the_shared_data.stop_if_no_time = stopIfNoTime;
//	the_shared_data.i_am_dead = false;
    
//
// We will push change event on State and Cumulated Value attributes
//


    Tango::Attribute &state_att = dev_attr->get_attr_by_name("state");
    state_att.set_change_event(true,false);

    
//	Tango::Attribute &val_att = dev_attr->get_attr_by_name("CumulatedValue");
//	val_att.set_change_event(true);
        
//
// Build the PoolBaseUtils class depending on the
// controller type

//

    set_utils(new TwoDExpChannelUtil(pool_dev));

    
//
// Inform Pool of our birth
//

    Pool_ns::TwoDExpChannelPool *twod_pool_ptr = new Pool_ns::TwoDExpChannelPool;
    init_pool_element(twod_pool_ptr);

    
    
    
    {
        Tango::AutoTangoMonitor atm(pool_dev);
        pool_dev->add_element(twod_pool_ptr);
    }

//
// Inform controller of our birth
//

    a_new_child(twod_pool_ptr->get_ctrl_id());
    
//
// If we are called due to a init command, update our info in the
// ghost group
//
        
    if (init_cmd == true)
    {
        MeasurementGroup_ns::MeasurementGroup *ghost_ptr = pool_dev->get_ghost_measurement_group_ptr();
        {
            Tango::AutoTangoMonitor atm(ghost_ptr);
            ghost_ptr->add_twod_to_ghost_group(get_id());
        }
        init_cmd = false;
    }
    
}

Pool_ns::TwoDExpChannelPool &TwoDExpChannel::get_twod_element()
{
    return static_cast<Pool_ns::TwoDExpChannelPool &>(get_pool_element());
}

//+----------------------------------------------------------------------------
//
// method : 		TwoDExpChannel::get_device_property()
// 
// description : 	Read the device properties from database.
//
//-----------------------------------------------------------------------------
void TwoDExpChannel::get_device_property()
{
    //	Initialize your default values here (if not done with  POGO).
    //------------------------------------------------------------------
    PoolIndBaseDev::get_device_property();
    
    //	Read device properties from database.(Automatic code generation)
    //------------------------------------------------------------------
    Tango::DbData	dev_prop;
    dev_prop.push_back(Tango::DbDatum("MaxXDim"));
    dev_prop.push_back(Tango::DbDatum("MaxYDim"));

    //	Call database and extract values
    //--------------------------------------------
    if (Tango::Util::instance()->_UseDb==true)
        get_db_device()->get_property(dev_prop);
    Tango::DbDatum	def_prop, cl_prop;
    TwoDExpChannelClass	*ds_class =
        (static_cast<TwoDExpChannelClass *>(get_device_class()));
    int	i = -1;

    //	Try to initialize MaxXDim from class property
    cl_prop = ds_class->get_class_property(dev_prop[++i].name);
    if (cl_prop.is_empty()==false)	cl_prop  >>  maxXDim;
    //	Try to initialize MaxXDim from default device value
    def_prop = ds_class->get_default_device_property(dev_prop[i].name);
    if (def_prop.is_empty()==false)	def_prop  >>  maxXDim;
    //	And try to extract MaxXDim value from database
    if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  maxXDim;

    //	Try to initialize MaxYDim from class property
    cl_prop = ds_class->get_class_property(dev_prop[++i].name);
    if (cl_prop.is_empty()==false)	cl_prop  >>  maxYDim;
    //	Try to initialize MaxYDim from default device value
    def_prop = ds_class->get_default_device_property(dev_prop[i].name);
    if (def_prop.is_empty()==false)	def_prop  >>  maxYDim;
    //	And try to extract MaxYDim value from database
    if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  maxYDim;



    //	End of Automatic code generation
    //------------------------------------------------------------------

}

//+----------------------------------------------------------------------------
//
// method : 		TwoDExpChannel::always_executed_hook()
// 
// description : 	method always executed before any command is executed
//
//-----------------------------------------------------------------------------
void TwoDExpChannel::always_executed_hook()
{
    
}
//+----------------------------------------------------------------------------
//
// method : 		TwoDExpChannel::read_attr_hardware
// 
// description : 	Hardware acquisition for attributes.
//
//-----------------------------------------------------------------------------
void TwoDExpChannel::read_attr_hardware(vector<long> &attr_list)
{
    DEBUG_STREAM << "TwoDExpChannel::read_attr_hardware(vector<long> &attr_list) entering... "<< endl;
    //	Add your own code here	
    
    Tango::DevState old_state = get_state();
/*	
    if (old_state != Tango::MOVING)
    {
        bool th_dead;	
        {
            omni_mutex_lock lo(the_mutex);
            th_dead = the_shared_data.i_am_dead;
        }

//
// If the thread is dead,reclaim its memory
//
    
        if ((th_dead == true) && (th != NULL))
        {
            void *ptr;		
            th->join(&ptr);
            th = NULL;
        }
        
        base_always_executed_hook(false,false);
        Tango::DevState local_state = get_state();
        if ((local_state != Tango::ON) && 
            (local_state != Tango::FAULT) &&
            (local_state != Tango::UNKNOWN))
        {
            set_state(Tango::FAULT);
            unknown_state = true;
        }
    }
*/   

    base_always_executed_hook(false);

    
    inform_ghost(old_state,get_state());

}

//+----------------------------------------------------------------------------
//
// method : 		TwoDExpChannel::inform_ghost
// 
// description : 	inform ghost group of a change in the state
//
//-----------------------------------------------------------------------------

void TwoDExpChannel::inform_ghost(Tango::DevState old_state,Tango::DevState new_state)
{
    if (old_state != Tango::MOVING)
    {
        if(old_state != new_state && 
           new_state != Tango::ON &&
           new_state != Tango::MOVING)
        {
            try
            {
                MeasurementGroup_ns::MeasurementGroup *ghost = pool_dev->get_ghost_measurement_group_ptr();
                long idx = ghost->get_ind_elt_idx_from_id(get_id());
                Tango::AutoTangoMonitor synch(ghost);
                ghost->update_state_from_ctrls(idx,new_state);
            }
            catch(Tango::DevFailed &df)
            { /* if ghost is not yet created then no choice but to ignore this */ }
        }
    }
}

//+------------------------------------------------------------------
/**
 *	method:	TwoDExpChannel::dev_status
 *
 *	description:	method to execute "Status"
 *	This command gets the device status (stored in its <i>device_status</i> data member) and returns it to the caller.
 *
 * @return	Status description
 *
 */
//+------------------------------------------------------------------
Tango::ConstDevString TwoDExpChannel::dev_status()
{
    Tango::ConstDevString	argout = DeviceImpl::dev_status();
    DEBUG_STREAM << "TwoDExpChannel::dev_status(): entering... !" << endl;

    //	Add your own code to control device here

    base_dev_status(argout);


    argout = tmp_status.c_str();
    return argout;
}

//+----------------------------------------------------------------------------
//
// method : 		TwoDExpChannel::read_XDim
// 
// description : 	Extract real attribute values for XDim acquisition result.
//
//-----------------------------------------------------------------------------
void TwoDExpChannel::read_XDim(Tango::Attribute &attr)
{
    DEBUG_STREAM << "TwoDExpChannel::read_XDim(Tango::Attribute &attr) entering... "<< endl;	
    
    Pool_ns::TwoDExpChannelPool &twod_element = get_twod_element();
    
    string par_name("XDim");

    if (!twod_element.get_simulation_mode())
    {
            
        Pool_ns::AutoPoolLock lo(fica_ptr->get_mon());
        Controller::CtrlData tmp_val;
        try
        { 
            TwoDController *typed_ctrl = static_cast<TwoDController *>(twod_element.get_controller());
            tmp_val = typed_ctrl->GetPar(get_axis(),par_name);
        }
        SAFE_CATCH(fica_ptr->get_name(),"read_XDim");

        if (tmp_val.int32_data == 0x7fffffffL)
        {
            Tango::Except::throw_exception((const char *)"TwoDExpChannel_BadController",
                                           (const char *)"The TwoDExpChannel controller class has not re-defined method to get TwoDExpChannel parameters",
                                           (const char *)"TwoDExpChannel::XDim");
        }
        
	switch(tmp_val.data_type){
	    case 1: // integer
	    {
		attr_XDim_write = tmp_val.int32_data;
	    }
	    break;
	    case 2:
	    {
		attr_XDim_write = int(tmp_val.db_data);
	    }
	    break;
	    default:
	    {
		Tango::Except::throw_exception((const char *)"TwoDExpChannel_BadController",
					       (const char *)"Wrong data type",
					       (const char *)"TwoDExpChannel::XDim");
	    } 
	}
    }

    attr.set_value( &attr_XDim_write );
}

//+----------------------------------------------------------------------------
//
// method : 		TwoDExpChannel::write_XDim
// 
// description : 	Write XDim attribute values to hardware.
//
//-----------------------------------------------------------------------------
void TwoDExpChannel::write_XDim(Tango::WAttribute &attr)
{
    DEBUG_STREAM << "TwoDExpChannel::write_XDim(Tango::WAttribute &attr) entering... "<< endl;

    Pool_ns::TwoDExpChannelPool &twod_element = get_twod_element();

    attr.get_write_value( attr_XDim_write);
    if (attr_XDim_write <= 0)
    {
        Tango::Except::throw_exception((const char *)"TwoDExpChannel_BadArgument",
                                       (const char *)"XDim cannot be negative or null",
                                       (const char *)"TwoDExpChannel::write_XDim");
    }

    string par_name("XDim");
    Controller::CtrlData tmp_data;
    tmp_data.data_type = Controller::INT32;
    tmp_data.int32_data = attr_XDim_write;
    if (!twod_element.get_simulation_mode())
    {
        
        Pool_ns::AutoPoolLock lo(fica_ptr->get_mon());	
        
        try
        {
            TwoDController *typed_ctrl = static_cast<TwoDController *>(twod_element.get_controller());
            typed_ctrl->SetPar(get_axis(),par_name,tmp_data);              
        }
        SAFE_CATCH(fica_ptr->get_name(),"write_XDim");
    }  

}

//+----------------------------------------------------------------------------
//
// method : 		TwoDExpChannel::read_YDim
// 
// description : 	Extract real attribute values for YDim acquisition result.
//
//-----------------------------------------------------------------------------
void TwoDExpChannel::read_YDim(Tango::Attribute &attr)
{
    DEBUG_STREAM << "TwoDExpChannel::read_YDim(Tango::Attribute &attr) entering... "<< endl;
    
    Pool_ns::TwoDExpChannelPool &twod_element = get_twod_element();
    
    string par_name("YDim");
    if (!twod_element.get_simulation_mode())
    {
            
        Pool_ns::AutoPoolLock lo(fica_ptr->get_mon());
        Controller::CtrlData tmp_val;
        try
        {
            TwoDController *typed_ctrl = static_cast<TwoDController *>(twod_element.get_controller());				
            tmp_val = typed_ctrl->GetPar(get_axis(),par_name);
        }
        SAFE_CATCH(fica_ptr->get_name(),"read_YDim");
        
        if (tmp_val.int32_data == 0x7fffffffL)
        {
            Tango::Except::throw_exception((const char *)"TwoDExpChannel_BadController",
                                           (const char *)"The TwoDExpChannel controller class has not re-defined method to get TwoDExpChannel parameters",
                                           (const char *)"TwoDExpChannel::YDim");
        }
	switch(tmp_val.data_type){
	    case 1: // integer
	    {
		attr_YDim_write = tmp_val.int32_data;
	    }
	    break;
	    case 2:
	    {
		attr_YDim_write = int(tmp_val.db_data);
	    }
	    break;
	    default:
	    {
		Tango::Except::throw_exception((const char *)"TwoDExpChannel_BadController",
					       (const char *)"Wrong data type",
					       (const char *)"TwoDExpChannel::XDim");
	    } 
	}
    }

    attr.set_value( &attr_YDim_write );
}

//+----------------------------------------------------------------------------
//
// method : 		TwoDExpChannel::write_YDim
// 
// description : 	Write YDim attribute values to hardware.
//
//-----------------------------------------------------------------------------
void TwoDExpChannel::write_YDim(Tango::WAttribute &attr)
{
    DEBUG_STREAM << "TwoDExpChannel::write_YDim(Tango::WAttribute &attr) entering... "<< endl;

    Pool_ns::TwoDExpChannelPool &twod_element = get_twod_element();
    
    attr.get_write_value( attr_YDim_write);
    if (attr_YDim_write <= 0)
    {
        Tango::Except::throw_exception((const char *)"TwoDExpChannel_BadArgument",
                                       (const char *)"YDim cannot be negative or null",
                                       (const char *)"TwoDExpChannel::write_YDim");
    }

    string par_name("YDim");
    Controller::CtrlData tmp_data;
    tmp_data.data_type = Controller::INT32;
    tmp_data.int32_data = attr_YDim_write;
    if (!twod_element.get_simulation_mode())
    {
        
        Pool_ns::AutoPoolLock lo(fica_ptr->get_mon());	
        
        try
        {
            TwoDController *typed_ctrl = static_cast<TwoDController *>(twod_element.get_controller());
            typed_ctrl->SetPar(get_axis(),par_name,tmp_data);              
        }
        SAFE_CATCH(fica_ptr->get_name(),"write_YDim");
    }  

}


//+----------------------------------------------------------------------------
//
// method : 		TwoDExpChannel::read_IFormat
// 
// description : 	Extract real attribute values for IFormat acquisition result.
//
//-----------------------------------------------------------------------------
void TwoDExpChannel::read_IFormat(Tango::Attribute &attr)
{
    DEBUG_STREAM << "TwoDExpChannel::read_XDim(Tango::Attribute &attr) entering... "<< endl;

    Pool_ns::TwoDExpChannelPool &twod_element = get_twod_element();
    
    string par_name("IFormat");
    if (!twod_element.get_simulation_mode())
    {
            
        Pool_ns::AutoPoolLock lo(fica_ptr->get_mon());
        Controller::CtrlData tmp_val;
        try
        {
            TwoDController *typed_ctrl = static_cast<TwoDController *>(twod_element.get_controller());
            tmp_val = typed_ctrl->GetPar(get_axis(),par_name);
        }
        SAFE_CATCH(fica_ptr->get_name(),"read_IFormat");
        
        if (tmp_val.int32_data == 0x7fffffffL)
        {
            Tango::Except::throw_exception((const char *)"TwoDExpChannel_BadController",
                                           (const char *)"The TwoDExpChannel controller class has not re-defined method to get TwoDExpChannel parameters",
                                           (const char *)"TwoDExpChannel::IFormat");
        }
        attr_IFormat_write = tmp_val.int32_data;
    }

    attr.set_value( &attr_IFormat_write );
}

//+----------------------------------------------------------------------------
//
// method : 		TwoDExpChannel::write_IFormat
// 
// description : 	Write IFormat attribute values to hardware.
//
//-----------------------------------------------------------------------------
void TwoDExpChannel::write_IFormat(Tango::WAttribute &attr)
{
    DEBUG_STREAM << "TwoDExpChannel::write_IFormat(Tango::WAttribute &attr) entering... "<< endl;

    Pool_ns::TwoDExpChannelPool &twod_element = get_twod_element();
    
    attr.get_write_value( attr_IFormat_write);
    if (attr_IFormat_write <= 0)
    {
        Tango::Except::throw_exception((const char *)"TwoDExpChannel_BadArgument",
                                       (const char *)"IFormat cannot be negative or null",
                                       (const char *)"TwoDExpChannel::write_IFormat");
    }

    string par_name("IFormat");
    Controller::CtrlData tmp_data;
    tmp_data.data_type = Controller::INT32;
    tmp_data.int32_data = attr_IFormat_write;
    if (!twod_element.get_simulation_mode())
    {
        
        Pool_ns::AutoPoolLock lo(fica_ptr->get_mon());	
        
        try
        {
            TwoDController *typed_ctrl = static_cast<TwoDController *>(twod_element.get_controller());
            typed_ctrl->SetPar(get_axis(),par_name,tmp_data);              
        }
        SAFE_CATCH(fica_ptr->get_name(),"write_IFormat");
    }  

}


//+----------------------------------------------------------------------------
//
// method : 		TwoDExpChannel::read_Value
// 
// description : 	Extract real attribute values for Value acquisition result.
//
//-----------------------------------------------------------------------------
void TwoDExpChannel::read_Value(Tango::Attribute &attr)
{
    DEBUG_STREAM << "TwoDExpChannel::read_Value(Tango::Attribute &attr) entering... "<< endl;
    
    Pool_ns::TwoDExpChannelPool &twod_element = get_twod_element();
    
    if (!twod_element.get_simulation_mode())
    {
        
//
// If we are not acquiring data, returns the value coming from the controller
//
        
        Pool_ns::AutoPoolLock lo(fica_ptr->get_mon());
        string par_namex("XDim");
        string par_namey("YDim");
        string par_format("IFormat");
        Controller::CtrlData tmp_valx;
        Controller::CtrlData tmp_valy;
        Controller::CtrlData tmp_format;
        try
        {
            TwoDController *typed_ctrl = static_cast<TwoDController *>(twod_element.get_controller());
            
            typed_ctrl->PreReadAll();
            typed_ctrl->PreReadOne(get_axis());
            typed_ctrl->ReadAll();
         
            attr_Value_read = (Tango::DevDouble*)typed_ctrl->ReadOne(get_axis());

            tmp_valx = typed_ctrl->GetPar(get_axis(),par_namex);
            tmp_valy = typed_ctrl->GetPar(get_axis(),par_namey);
            tmp_format = typed_ctrl->GetPar(get_axis(),par_format);

        }
        SAFE_CATCH(fica_ptr->get_name(),"read_Value");
        
        if ( (tmp_valx.int32_data == 0x7fffffffL) || (tmp_valy.int32_data == 0x7fffffffL))
        {
            Tango::Except::throw_exception((const char *)"TwoDExpChannel_BadController",
                                           (const char *)"The TwoDExpChannel controller class has not re-defined method to get TwoDExpChannel parameters",
                                           (const char *)"TwoDExpChannel::read_Value");
        }
        attr_XDim_write = tmp_valx.int32_data;
        attr_YDim_write = tmp_valy.int32_data;
        attr_IFormat_write = tmp_format.int32_data;

        if(attr_Value_read == NULL)
        {
            Tango::Except::throw_exception((const char *)"TwoDExpChannel_BadController",
                                           (const char *)"The Two D Exp Channel controller class has not re-defined method to read value (ReadOne(...))",
                                           (const char *)"TwoDExpChannel::read_Value");
        }

    }
    else
    {
        *attr_Value_read = 0.0;
    }

    attr.set_value(attr_Value_read, attr_XDim_write, attr_YDim_write);

}


//+------------------------------------------------------------------
/**
 *	method:	TwoDExpChannel::start
 *
 *	description:	method to execute "Start"
 *	Start acquiring data
 *
 *
 */
//+------------------------------------------------------------------
void TwoDExpChannel::start()
{
    DEBUG_STREAM << "TwoDExpChannel::start(): entering... !" << endl;

    //	Add your own code to control device here
    
    Pool_ns::TwoDExpChannelPool &twod_element = get_twod_element();
    
    if (!twod_element.get_simulation_mode())
    {

        Pool_ns::AutoPoolLock lo(fica_ptr->get_mon());
        
        try
        {
            TwoDController *typed_ctrl = static_cast<TwoDController *>(twod_element.get_controller());

            typed_ctrl->StartOne(get_axis());
        }
        SAFE_CATCH(fica_ptr->get_name(),"start");
        set_state(Tango::MOVING);
        Tango::MultiAttribute *dev_attrs = get_device_attr();
        Tango::Attribute &state_att = dev_attrs->get_attr_by_name("State");
        state_att.fire_change_event();
        
    }
    else
    {
        Tango::Except::throw_exception((const char *)"TwoDExpChannel_SimuMode",
                                       (const char *)"Command not allowed when in simulation mode",
                                       (const char *)"TwoDExpChannel::start");
    }
    
    
    
}

//+------------------------------------------------------------------
/**
 *	method:	TwoDExpChannel::abort
 *
 *	description:	method to execute "Abort"
 *	Stop acquiring data
 *
 *
 */
//+------------------------------------------------------------------
void TwoDExpChannel::abort()
{
    DEBUG_STREAM << "TwoDExpChannel::abort(): entering... !" << endl;

    //	Add your own code to control device here
    base_abort(true);
}


//+------------------------------------------------------------------
/**
 *	method:	TwoDExpChannel::base_abort
 *
 *	description:	method to execute "Abort"
 *	Stop acquiring data
 *
 *
 */
//+------------------------------------------------------------------
void TwoDExpChannel::base_abort(bool send_evt)
{
    Pool_ns::TwoDExpChannelPool &twod_element = get_twod_element();
    
    if (!twod_element.get_simulation_mode())
    {
        
        Pool_ns::AutoPoolLock lo(fica_ptr->get_mon());
        
        try
        {
            TwoDController *typed_ctrl = static_cast<TwoDController *>(twod_element.get_controller());

            typed_ctrl->AbortOne(get_axis());
        }
        SAFE_CATCH(fica_ptr->get_name(),"abort");
        
        Tango::MultiAttribute *dev_attrs = get_device_attr();
        set_state(Tango::ON);
        Tango::Attribute &state_att = dev_attrs->get_attr_by_name("State");
        state_att.fire_change_event();
        
    }
    else
    {
        Tango::Except::throw_exception((const char *)"TwoDExpChannel_SimuMode",
                                       (const char *)"Command not allowed when in simulation mode",
                                       (const char *)"TwoDExpChannel::abort");
    }

    
    if(send_evt)
    {
        set_state(Tango::ON);
        Tango::MultiAttribute *dev_attrs = get_device_attr();
        Tango::Attribute &state_att = dev_attrs->get_attr_by_name("State");
        state_att.fire_change_event();

    }
}

TwoDExpChannel::Simu_data::Simu_data(TwoDExpChannel *chan):channel(chan)
{
    Tango::AutoTangoMonitor atm(channel);
    
//	simu_time = channel->attr_CumulationTime_write;
//	simu_type = channel->attr_CumulationType_write;
}

TwoDExpChannel::Simu_data::~Simu_data()
{
/*	
    Tango::AutoTangoMonitor atm(channel);
    
    Tango::MultiAttribute *ma_ptr = channel->get_device_attr();
    if (channel->attr_CumulationTime_write != simu_time)
    {
        channel->attr_CumulationTime_write = simu_time;
        Tango::WAttribute &att = ma_ptr->get_w_attr_by_name("CumulationTime");
        att.set_write_value(simu_time);
    }
    
    if (channel->attr_CumulationType_write != simu_type)
    {
        channel->attr_CumulationType_write = simu_type;
        Tango::WAttribute &att = ma_ptr->get_w_attr_by_name("CumulationType");
        att.set_write_value(simu_type);
    }
*/
}

}	//	namespace
