#!/usr/bin/env python

"""The Spock startup file. This executable is actually an extension of the 
   ipython file that can be found in <prefix>/ipython (prefix usually being in 
   linux '/usr/bin'"""

def main():
    import spocklib.genutils
    spocklib.genutils.run()
    
if __name__ == '__main__':
    main()
